/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  formidableSidebar: [
    {
      type: 'autogenerated',
      dirName: 'formidable',
    },
  ],
};

export default sidebars;